title: Freddy Medina
logo: Assets/a guy with glasses, plain background color like white, gray, etc., looking at an angle, face only above the neck.png
description: Estudiante de Ingeniería
#show_downloads: false
theme: Jekyll-theme-minimal
